-- call this procedure to grab x number of new locations and populate the coordinates into the specified table
call get_n_random_locs(20, 'random_20_locs');

-- call this procedure to generate the nearest neighbor flight path
call naive_path_finder('random_20_locs');

-- call this procedure to generate the gentics algorithm flight path, feel free to tweak 
-- parameters and rerun the algorithm to see how different parameters affect the final output
call genetics_path_finder('random_20_locs', 250, 100, 0.01);

-- query this table to see the flight paths and total distances generated by the nearest neighbor and genetics algorihms
select * from routes.random_20_locs_route;